"""
backend/plato/schemas.py
Stage 9 — Pydantic schemas for Plato pipeline data types.

Separated from SQLAlchemy models so the pipeline can run without a live DB
session (e.g. unit tests, export-only runs).
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, model_validator


# ---------------------------------------------------------------------------
# WSFT training data
# ---------------------------------------------------------------------------

class TrainingExample(BaseModel):
    """
    One weighted supervised fine-tuning example.
    input_text  : formatted prompt fed to Plato during fine-tuning
    output_text : expected refined-problem JSON string
    weight      : utility_score — higher = stronger gradient signal
    source_id   : UUID of the originating plato_log row (for audit)
    """
    source_id: uuid.UUID
    input_text: str
    output_text: str
    weight: float = Field(..., ge=0.0, le=1.0)
    topic: str = ""
    failure_mode: str = ""

    @model_validator(mode="after")
    def output_must_be_json_parseable(self) -> "TrainingExample":
        import json
        try:
            json.loads(self.output_text)
        except (ValueError, TypeError) as exc:
            raise ValueError(
                f"output_text is not valid JSON for source_id={self.source_id}: {exc}"
            ) from exc
        return self


# ---------------------------------------------------------------------------
# Generation pipeline
# ---------------------------------------------------------------------------

class CandidateProblem(BaseModel):
    """
    A problem variant generated by Plato, prior to DB insertion.
    Matches the RefinedProblem dataclass from brain_b.py but as Pydantic.
    """
    title: str
    statement: str
    difficulty: float = Field(..., ge=0.0, le=1.0)
    solution: str
    answer: str
    visible_tests: List[Dict[str, Any]] = Field(default_factory=list)
    hidden_tests: List[Dict[str, Any]] = Field(default_factory=list)
    topic: str = ""
    utility_score: float = 0.0
    source_problem_id: Optional[uuid.UUID] = None
    content_hash: Optional[str] = None


class GenerationResult(BaseModel):
    """
    Summary of one generation run for a single source problem.
    """
    source_problem_id: uuid.UUID
    topic: str
    source_difficulty: float
    candidates_generated: int
    candidates_accepted: int
    candidates_rejected: int
    inserted_ids: List[str] = Field(default_factory=list)
    errors: List[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Training run results
# ---------------------------------------------------------------------------

class TrainingRunResult(BaseModel):
    """
    Structured result returned by PlatoTrainer.run() regardless of outcome.
    Avoids crash-on-failure; callers inspect `success` and `message`.
    """
    success: bool
    message: str
    total_rows_fetched: int = 0
    rows_skipped: int = 0
    training_examples: int = 0
    average_utility: float = 0.0
    artifact_path: Optional[str] = None
    timestamp: datetime = Field(default_factory=datetime.utcnow)


# ---------------------------------------------------------------------------
# Export dataset record (JSONL line format)
# ---------------------------------------------------------------------------

class DatasetRecord(BaseModel):
    """
    One line in the exported JSONL training dataset.
    Compatible with HuggingFace datasets / trl SFTTrainer input format.
    """
    prompt: str           # full formatted input
    completion: str       # refined problem JSON string
    weight: float         # sample weight == utility_score
    metadata: Dict[str, Any] = Field(default_factory=dict)
