"""Initial schema base

Revision ID: 613fcf2ad7fd
Revises: 
Create Date: 2026-03-31 09:42:13.296675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '613fcf2ad7fd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('statement', sa.String(), nullable=False),
    sa.Column('visible_tests', sa.JSON(), nullable=False),
    sa.Column('hidden_tests', sa.JSON(), nullable=False),
    sa.Column('prerequisite_topics', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Enum('plato', 'human', name='createdby', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problems_topic'), 'problems', ['topic'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('student', 'instructor', name='userrole', native_enum=False), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('capability_vectors',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capability_vectors_topic'), 'capability_vectors', ['topic'], unique=False)
    op.create_table('plato_logs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('original_problem_id', sa.Uuid(), nullable=False),
    sa.Column('failure_mode', sa.String(), nullable=False),
    sa.Column('refined_problem', sa.JSON(), nullable=False),
    sa.Column('utility_score', sa.Float(), nullable=False),
    sa.Column('used_in_training', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['original_problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fatigue_score', sa.Float(), nullable=False),
    sa.Column('consecutive_fails', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submissions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('problem_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('visible_score', sa.Float(), nullable=False),
    sa.Column('hidden_score', sa.Float(), nullable=False),
    sa.Column('brain_a_feedback', sa.String(), nullable=False),
    sa.Column('gamed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_metrics',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('pre_test_score', sa.Float(), nullable=False),
    sa.Column('post_test_score', sa.Float(), nullable=False),
    sa.Column('confidence_rating', sa.Integer(), nullable=False),
    sa.Column('time_to_solve', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_metrics')
    op.drop_table('submissions')
    op.drop_table('sessions')
    op.drop_table('plato_logs')
    op.drop_index(op.f('ix_capability_vectors_topic'), table_name='capability_vectors')
    op.drop_table('capability_vectors')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_problems_topic'), table_name='problems')
    op.drop_table('problems')
    # ### end Alembic commands ###
