"""add_dialogue_sessions_uuid_final

Revision ID: b21ff5c1a08b
Revises: 613fcf2ad7fd
Create Date: 2026-03-31 23:54:53.979220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b21ff5c1a08b'
down_revision: Union[str, Sequence[str], None] = '613fcf2ad7fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialogue_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('history', sa.JSON(), nullable=False),
    sa.Column('root_cause', sa.String(length=512), nullable=False, comment='Conceptual gap identified by Brain B during error analysis'),
    sa.Column('target_insight', sa.String(length=512), nullable=False, comment='One-sentence rubric Brain A checks student responses against'),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', 'EXHAUSTED', name='dialoguestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dialogue_sessions_id'), 'dialogue_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_dialogue_sessions_status'), 'dialogue_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_dialogue_sessions_submission_id'), 'dialogue_sessions', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dialogue_sessions_submission_id'), table_name='dialogue_sessions')
    op.drop_index(op.f('ix_dialogue_sessions_status'), table_name='dialogue_sessions')
    op.drop_index(op.f('ix_dialogue_sessions_id'), table_name='dialogue_sessions')
    op.drop_table('dialogue_sessions')
    # ### end Alembic commands ###
